# Generated by Django 4.2 on 2023-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stats_outside_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='outside_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
